HongDam-org/TWTW

.github/workflows/backend-ci.yml, .github/workflows/reformat-google-java-format.yml
- github actions
- CI
- Reformat code
=> [FEAT] reformat and ci github actions

backend/build.gradle, backend/src/docs/index.adoc, backend/src/test/java/com/twtw/backend/support/docs/ApiDocsUtils.java, backend/src/test/java/com/twtw/backend/support/docs/RestDocsConfig.java, backend/src/test/java/com/twtw/backend/support/docs/RestDocsTest.java
=> [FEAT] rest docs 세팅

backend/src/docs/index.adoc, backend/src/docs/plan.adoc, backend/src/test/java/com/twtw/backend/domain/plan/controller/PlanControllerTest.java, backend/src/test/java/com/twtw/backend/support/docs/RestDocsTest.java
- 키워드와 카테고리를 통한 장소 검색 Rest Docs 작성
- 없음
=> [FEAT] search map api docs

backend/src/docs/auth.adoc, backend/src/docs/index.adoc, backend/src/docs/path.adoc, backend/src/test/java/com/twtw/backend/domain/member/controller/AuthControllerTest.java, backend/src/test/java/com/twtw/backend/domain/path/controller/PathControllerTest.java
- Auth와 Path API Docs
- Path Dto 채워넣어야 함
=> [DOCS] auth and path api docs

backend/build.gradle, backend/src/main/java/com/twtw/backend/config/properties/PropertiesConfig.java, backend/src/main/java/com/twtw/backend/config/security/SecurityConfig.java, backend/src/main/java/com/twtw/backend/domain/path/client/SearchCarPathClient.java, backend/src/main/java/com/twtw/backend/domain/path/client/SearchPedPathClient.java, backend/src/main/java/com/twtw/backend/domain/path/controller/PathController.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/Position.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/ResponsePositionFormat.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/RouteUnitEnt.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchCarPathRequest.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchCarPathResponse.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchPathFuel.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchPathOption.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SectionUnit.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/Summary.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/Geometry.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/SearchPedPathRequest.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/SearchPedPathResponse.java, backend/src/main/java/com/twtw/backend/domain/path/service/PathService.java, backend/src/main/java/com/twtw/backend/global/properties/TmapProperties.java
env.yml 파일 별도 정리
tmap 보행자 경로 api에 대해서만 구현
=> [FEAT] tmap api 연동 및 보행자 경로 로직 구현

backend/src/docs/auth.adoc, backend/src/main/java/com/twtw/backend/config/security/jwt/TokenProvider.java, backend/src/main/java/com/twtw/backend/domain/member/controller/AuthController.java, backend/src/main/java/com/twtw/backend/domain/member/exception/RefreshTokenInfoMatchException.java, backend/src/main/java/com/twtw/backend/domain/member/exception/RefreshTokenInfoMissMatchException.java, backend/src/main/java/com/twtw/backend/domain/member/exception/RefreshTokenValidationException.java, backend/src/main/java/com/twtw/backend/domain/member/service/AuthService.java, backend/src/main/java/com/twtw/backend/global/exception/AuthorityException.java, backend/src/test/java/com/twtw/backend/domain/member/controller/AuthControllerTest.java
1. Refresh Token : Validation Exception
2. Refresh Token : InfoMatch Exception
3. Token Authority Exception
=> [FEAT] auth exception

backend/src/main/java/com/twtw/backend/global/advice/ErrorResponse.java, backend/src/main/java/com/twtw/backend/global/advice/GlobalErrorAdvice.java, backend/src/main/java/com/twtw/backend/global/exception/EntityNotFoundException.java
- GlobalErrorAdvice
- ErrorResponse dto
- EntityNotFoundException
- EntityNotFoundException 은 어차피 쓰일 것이라서 미리 만듬
=> [FEAT] global advice 및 ErrorResponse dto

backend/build.gradle, backend/src/main/java/com/twtw/backend/domain/member/controller/AuthController.java, backend/src/main/java/com/twtw/backend/domain/member/dto/request/MemberSaveRequest.java, backend/src/main/java/com/twtw/backend/domain/member/dto/request/OAuthRequest.java, backend/src/main/java/com/twtw/backend/domain/member/dto/request/TokenRequest.java, backend/src/main/java/com/twtw/backend/domain/path/controller/PathController.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/car/SearchCarPathRequest.java, backend/src/main/java/com/twtw/backend/domain/path/dto/client/ped/SearchPedPathRequest.java
1. DTO Validation 의존성 추가
2. AUTH + PATH Controller 추가
=> [FEAT] DTO Validation 의존성 추가 + AUTH + PATH Controller 추가

backend/build.gradle, backend/src/main/java/com/twtw/backend/config/database/QuerydslConfig.java, backend/src/main/java/com/twtw/backend/domain/friend/controller/FriendController.java, backend/src/main/java/com/twtw/backend/domain/friend/dto/request/FriendRequest.java, backend/src/main/java/com/twtw/backend/domain/friend/dto/request/FriendUpdateRequest.java, backend/src/main/java/com/twtw/backend/domain/friend/dto/response/FriendResponse.java, backend/src/main/java/com/twtw/backend/domain/friend/entity/Friend.java, backend/src/main/java/com/twtw/backend/domain/friend/entity/FriendStatus.java, backend/src/main/java/com/twtw/backend/domain/friend/exception/InvalidFriendMemberException.java, backend/src/main/java/com/twtw/backend/domain/friend/mapper/FriendMapper.java, backend/src/main/java/com/twtw/backend/domain/friend/repository/FriendQueryRepository.java, backend/src/main/java/com/twtw/backend/domain/friend/repository/FriendQueryRepositoryImpl.java, backend/src/main/java/com/twtw/backend/domain/friend/repository/FriendRepository.java, backend/src/main/java/com/twtw/backend/domain/friend/service/FriendService.java
- querydsl 설정
- friend 엔티티
- friend api 구현
- static import 원래 안좋아하지만 querydsl 이라서 편의를 위해 샤용함
- 이후 rest docs 작업 예정
=> [FEAT] friend api and querydsl config

backend/src/main/java/com/twtw/backend/domain/group/dto/request/MakeGroupDto.java, backend/src/main/java/com/twtw/backend/domain/group/dto/response/GroupInfoDto.java, backend/src/main/java/com/twtw/backend/domain/group/entity/Group.java, backend/src/main/java/com/twtw/backend/domain/group/entity/GroupMember.java, backend/src/main/java/com/twtw/backend/domain/group/mapper/GroupMapper.java, backend/src/main/java/com/twtw/backend/domain/group/service/GroupService.java, backend/src/main/java/com/twtw/backend/domain/member/entity/Member.java, backend/src/test/java/com/twtw/backend/BackendApplicationTests.java, backend/src/test/java/com/twtw/backend/domain/member/controller/MemberControllerTest.java
=> [ADD] Group Service

backend/src/main/java/com/twtw/backend/config/rabbitmq/RabbitMQConfig.java, backend/src/main/java/com/twtw/backend/config/security/SecurityConfig.java, backend/src/main/java/com/twtw/backend/config/socket/StompConfig.java, backend/src/main/java/com/twtw/backend/config/web/WebConfig.java, backend/src/main/java/com/twtw/backend/domain/location/controller/LocationController.java, backend/src/main/java/com/twtw/backend/domain/location/dto/request/LocationRequest.java, backend/src/main/java/com/twtw/backend/domain/location/dto/response/LocationResponse.java, backend/src/main/java/com/twtw/backend/domain/location/mapper/LocationMapper.java, backend/src/main/java/com/twtw/backend/domain/location/service/LocationService.java
- Location 도메인 추가
- 소켓 연결 컨트롤러 추가
- 테스트 해봐야 함
=> [FEAT] location domain and socket config

backend/src/main/java/com/twtw/backend/config/rabbitmq/RabbitMQConfig.java, backend/src/main/java/com/twtw/backend/config/socket/StompConfig.java, backend/src/main/java/com/twtw/backend/domain/location/controller/LocationController.java
- STOMP 설정 수정
- STOMP 연결 테스트 완료
- 없음
=> [FEAT] location stomp 적용 완료

backend/src/test/java/com/twtw/backend/domain/group/controller/GroupControllerTest.java
=> [FEAT] Group API Docs

backend/src/main/java/com/twtw/backend/domain/group/entity/Group.java, backend/src/main/java/com/twtw/backend/domain/plan/entity/Plan.java
=> [FEAT] Group - Member connection

backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java
=> [FEAT] plans/search/destination API x와 y 값 null 처리

backend/src/main/java/com/twtw/backend/domain/group/controller/GroupController.java, backend/src/main/java/com/twtw/backend/domain/group/dto/request/InviteGroupRequest.java, backend/src/main/java/com/twtw/backend/domain/group/dto/request/JoinGroupRequest.java, backend/src/main/java/com/twtw/backend/domain/group/dto/request/MakeGroupRequest.java, backend/src/main/java/com/twtw/backend/domain/group/dto/response/GroupInfoResponse.java, backend/src/main/java/com/twtw/backend/domain/group/dto/response/ShareInfoResponse.java, backend/src/main/java/com/twtw/backend/domain/group/mapper/GroupMapper.java, backend/src/main/java/com/twtw/backend/domain/group/service/GroupService.java, backend/src/main/java/com/twtw/backend/domain/member/controller/AuthController.java, backend/src/main/java/com/twtw/backend/domain/member/controller/MemberController.java, backend/src/main/java/com/twtw/backend/domain/member/dto/response/AfterLoginResponse.java, backend/src/main/java/com/twtw/backend/domain/member/dto/response/DuplicateNicknameResponse.java, backend/src/main/java/com/twtw/backend/domain/member/dto/response/MemberResponse.java, backend/src/main/java/com/twtw/backend/domain/member/mapper/MemberMapper.java, backend/src/main/java/com/twtw/backend/domain/member/service/AuthService.java, backend/src/main/java/com/twtw/backend/domain/member/service/MemberService.java, backend/src/main/java/com/twtw/backend/domain/place/mapper/PlaceMapper.java, backend/src/main/java/com/twtw/backend/domain/place/service/PlaceService.java, backend/src/main/java/com/twtw/backend/domain/plan/controller/PlanController.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/request/PlanMemberRequest.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/response/PlanInfoResponse.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/response/PlanResponse.java, backend/src/main/java/com/twtw/backend/domain/plan/entity/Plan.java, backend/src/main/java/com/twtw/backend/domain/plan/mapper/PlanMapper.java, backend/src/main/java/com/twtw/backend/domain/plan/service/PlanService.java, backend/src/test/java/com/twtw/backend/domain/group/controller/GroupControllerTest.java, backend/src/test/java/com/twtw/backend/domain/member/controller/AuthControllerTest.java, backend/src/test/java/com/twtw/backend/domain/member/controller/MemberControllerTest.java
=> [FEAT] plan , group service fix

backend/src/main/java/com/twtw/backend/domain/friend/controller/advice/FriendControllerAdvice.java, backend/src/main/java/com/twtw/backend/domain/member/controller/AuthController.java, backend/src/main/java/com/twtw/backend/domain/member/controller/advice/AuthControllerAdvice.java, backend/src/main/java/com/twtw/backend/domain/member/exception/RefreshTokenInfoMismatchException.java, backend/src/main/java/com/twtw/backend/domain/member/service/AuthService.java, backend/src/main/java/com/twtw/backend/domain/plan/controller/PlanController.java, backend/src/main/java/com/twtw/backend/global/advice/GlobalErrorAdvice.java
- ControllerAdvice 빠진 부분 추가
- ResponseEntity 인라인 및 필요시 ok를 no content로 수정
- 없음
=> [FEAT] controller advice 추가 및 response entity 정리

backend/src/test/java/com/twtw/backend/fixture/friend/FriendEntityFixture.java, backend/src/test/java/com/twtw/backend/fixture/member/MemberEntityFixture.java, backend/src/test/java/com/twtw/backend/fixture/place/PlaceEntityFixture.java, backend/src/test/java/com/twtw/backend/fixture/plan/PlanEntityFixture.java
- Plan, Place, Friend 엔티티 Fixture 생성
- Member 엔티티 Fixture에 데이터 추가 하였음
=> [FEAT] 테스트를 위한 Fixture 생성

backend/src/main/java/com/twtw/backend/domain/plan/service/PlanService.java, backend/src/test/java/com/twtw/backend/domain/plan/repository/PlanRepositoryTest.java, backend/src/test/java/com/twtw/backend/fixture/plan/PlanEntityFixture.java, backend/src/test/java/com/twtw/backend/fixture/plan/PlanMemberEntityFixture.java, backend/src/test/java/com/twtw/backend/support/repository/RepositoryTest.java
=> [FEAT] repository 테스트 에러 수정

backend/src/main/java/com/twtw/backend/domain/group/entity/Group.java, backend/src/main/java/com/twtw/backend/domain/place/mapper/PlaceMapper.java, backend/src/main/java/com/twtw/backend/domain/plan/client/SearchDestinationClient.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/client/PlaceDetails.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/client/SearchDestinationRequest.java, backend/src/main/java/com/twtw/backend/domain/plan/entity/Plan.java, backend/src/main/java/com/twtw/backend/domain/plan/entity/PlanMember.java, backend/src/main/java/com/twtw/backend/domain/plan/exception/InvalidPlanMemberException.java, backend/src/test/java/com/twtw/backend/domain/place/controller/PlaceControllerTest.java, backend/src/test/java/com/twtw/backend/domain/plan/controller/PlanControllerTest.java, backend/src/test/java/com/twtw/backend/domain/plan/service/PlanServiceTest.java, backend/src/test/java/com/twtw/backend/fixture/place/PlaceDetailsFixture.java
- PlanService 테스트
- plan에 한 명만 존재하는 경우에 out plan을 수행할 때 어떻게 처리할지 생각해봐야함
=> [FEAT] plan service test

backend/src/main/java/com/twtw/backend/config/security/jwt/TokenProvider.java, backend/src/main/java/com/twtw/backend/domain/friend/repository/FriendQueryRepositoryImpl.java, backend/src/main/java/com/twtw/backend/domain/friend/service/FriendService.java, backend/src/test/java/com/twtw/backend/domain/friend/repository/FriendRepositoryTest.java, backend/src/test/java/com/twtw/backend/domain/friend/service/FriendServiceTest.java, backend/src/test/java/com/twtw/backend/domain/member/service/MemberServiceTest.java, backend/src/test/java/com/twtw/backend/domain/plan/service/PlanServiceTest.java, backend/src/test/java/com/twtw/backend/support/repository/EnableDataJpa.java, backend/src/test/java/com/twtw/backend/support/repository/RepositoryTest.java
- friend service repository 테스트
- 몇몇 테스트 에러 수정
=> [TEST] friend service repository 테스트

backend/src/test/java/com/twtw/backend/domain/path/service/PathServiceTest.java
=> [FEAT] Path Service Test

backend/src/main/java/com/twtw/backend/domain/plan/dto/request/SavePlanRequest.java, backend/src/main/java/com/twtw/backend/domain/plan/dto/response/PlanInfoResponse.java, backend/src/main/java/com/twtw/backend/domain/plan/entity/Plan.java, backend/src/main/java/com/twtw/backend/domain/plan/mapper/PlanMapper.java, backend/src/main/java/com/twtw/backend/domain/plan/service/PlanService.java, backend/src/test/java/com/twtw/backend/domain/group/repository/GroupRepositoryTest.java, backend/src/test/java/com/twtw/backend/domain/plan/controller/PlanControllerTest.java, backend/src/test/java/com/twtw/backend/domain/plan/repository/PlanRepositoryTest.java, backend/src/test/java/com/twtw/backend/domain/plan/service/PlanServiceTest.java, backend/src/test/java/com/twtw/backend/fixture/plan/PlanEntityFixture.java
=> [FIX] Plan에 planDay(yyyy-MM-dd HH:mm) 추가

backend/src/main/java/com/twtw/backend/domain/location/dto/collection/MemberDistances.java, backend/src/main/java/com/twtw/backend/domain/location/service/GeoService.java, backend/src/main/java/com/twtw/backend/domain/location/service/LocationService.java
- redis의 geo 타입을 사용하도록 수정
- 일급컬렉션 사용
=> [FEAT] redis geolocation을 사용한 좌표 거리 계산

backend/.gitignore, backend/build.gradle, backend/src/main/java/com/twtw/backend/config/firebase/FcmConfig.java, backend/src/main/java/com/twtw/backend/domain/group/service/GroupService.java, backend/src/main/java/com/twtw/backend/domain/notification/dto/NotificationRequest.java, backend/src/main/java/com/twtw/backend/domain/notification/mapper/NotificationMapper.java, backend/src/main/java/com/twtw/backend/domain/notification/service/FcmService.java, backend/src/test/java/com/twtw/backend/domain/path/service/PathServiceTest.java
1. Firebase 연동
2. FCM Service 기본 로직 구현
=> [FEAT] Firebase 연동 및 FCM Service 기본 Logic 구현

backend/src/main/java/com/twtw/backend/domain/group/controller/GroupController.java, backend/src/main/java/com/twtw/backend/domain/group/service/GroupService.java, backend/src/main/java/com/twtw/backend/domain/member/controller/MemberController.java, backend/src/main/java/com/twtw/backend/domain/member/service/MemberService.java, backend/src/main/java/com/twtw/backend/domain/plan/controller/PlanController.java, backend/src/main/java/com/twtw/backend/domain/plan/service/PlanService.java
=> [FEAT] Refactor cache
